### ISSUE TITLE
Course Edition : Thumbnail update 

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#109]
### Verified issue

- [X] Someone from the team allowed me to create an issue here

### Issue Content

Hi Everyone, 
Thanks for your interest in LearnHouse, this is a good first issue for anyone that want to contribute. 

### Issue Description:
The ability to update a course thumbnail 

### Difficulty Level: Easy/Intermediate/Advanced
Intermediate

### Expected Benefits:
Directly being able to update a course Thumbnail is an expected feature in basic websites. 

### Steps to Reproduce (if applicable):
Be able to update a Course thumbnail and seeing your changes live.

### Suggested UX:
- The page should now show the current  course thumbnail
- Hovering over the thumbnail would show a file upload icon 
- Clicking the thumbnail would allow for the user to select a file 
- Submitting would upload the file, you might add uploading indicators 

### Suggested Approach:

- Create a standalone custom component for uploading thumbnails, it would take `courseid` as props
   - The current thumbnail should show up first with a centered upload button 
   - When clicked, the upload process would immediately begin
   - The component should provide feedback about the state of the upload, a simple loader would work 
   - Update the thumbnail inside the component once the logo updated 
   - Use TailwindCSS
- Use `swr` to mutate data ``mutate(`${getAPIUrl()}courses/course_${courseid}`)`` once the thumbnail is updated 
- Revalidate tags & Router refresh (Next.js) 
```  
await revalidateTags(['courses'], course.org_slug)
router.refresh() 
```
- You might need to create a custom service here to update the thumbnail : https://github.com/learnhouse/learnhouse/blob/dev/apps/web/services/courses/courses.ts 

### Resources/References:

- CourseEditionPage : https://github.com/learnhouse/learnhouse/blob/dev/apps/web/app/orgs/%5Borgslug%5D/(withmenu)/course/%5Bcourseid%5D/edit/subpages/CourseEdition.tsx 
- CourseThumbnailBackend : https://github.com/learnhouse/learnhouse/blob/dev/apps/api/src/routers/courses/courses.py#L21

**Comment by kisharnath** [comment]
Hey @swve  I would like to work on this issue

**Comment by swve** [comment]
Hello @kisharnath sorry for the delay, just updated the issue with more context and references. 
Feel free to ask if you have any questions ;) 
Thanks for your interest

**Comment by swve** [comment]
Added here https://github.com/learnhouse/learnhouse/pull/140
