### ISSUE TITLE
[Bug]: Web Dockerfile problems

### ISSUE THREAD

**Issue by Rafael-Remigio** [learnhouse/learnhouse#142]
### What happened?

Dockerfile for building the node web app is using node version 16, the project requires 18.

```
FROM node:16-alpine
```

The project requires node version 18+.
Possible fix:
```
FROM node:18-alpine
```

The error I got was this when i tried to create and run the image from the Dockerfile.
```
docker run c070473135b9

    learnhouse@0.1.0 dev
    next dev


You are using Node.js 16.20.2. For Next.js, Node.js version >= v18.17.0 is required.
```

For some context here is my docker version:

```
$ docker version
Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:23 2024
 OS/Arch:           linux/amd64
 Context:           default
```

### Version

1.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swve** [comment]
Hey @Rafael-Remigio, thanks for reporting this! 🙏
I fixed it in https://github.com/learnhouse/learnhouse/commit/1271d792f07422184c6f30abf7b1dfc3f4f85343
