### ISSUE TITLE
Organization invites : Signed in users

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#146]
### Verified issue

- [X] Someone from the team allowed me to create an issue here

### Issue Content

Hi Everyone, 
Thanks for your interest in LearnHouse, this is a good first issue for anyone that want to contribute. 

### Issue Description:
The ability to join an organization from an invite code as a logged in user

### Difficulty Level: Easy/Intermediate/Advanced
Medium

### Expected Benefits:
Being able to join an organization from an invite code as a logged in user
There is 2 organizations, Org A and Org B : 
- From Org A and as an admin of that org, make the Org private from the UI and create an invite code. 
- Any user signed in in another org should be able to join that organization by simply clicking on the join button 

![image](https://github.com/learnhouse/learnhouse/assets/29493708/ecf5007d-2a38-47e0-beea-1847fd267e39)

### Suggested UX:
- The UX is already available to use here : https://github.com/learnhouse/learnhouse/blob/dev/apps/web/app/orgs/%5Borgslug%5D/signup/signup.tsx#L87 

### Suggested Approach:

- On click it should send a request to the backend with the invite code and the user, checks if the invite code is right and add the user to the org just like inthe provided context, but take as a parameter the user from `PublicUser : Depends(get_current_user)` instead of a `user_object of type UserCreate`, for context : https://github.com/learnhouse/learnhouse/blob/dev/apps/api/src/routers/users.py#L98  
- The new endpoint may be named : `@router.post("/{org_id}/invite/{invite_code}/logged_in")`

### Resources/References:

- Backend for creating a user with an invite code  : https://github.com/learnhouse/learnhouse/blob/dev/apps/api/src/routers/users.py#L98

**Comment by nvrthles** [comment]
Yes !

**Comment by swve** [comment]
> Yes ! @swve  How is the progress on this ?
> 
> 
> 
> 

No one really started working on this yet

**Comment by swve** [comment]
Alright i'll take this one
