### ISSUE TITLE
Add Tables feature to Editor

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#179]
### Verified issue

- [X] Someone from the team allowed me to create an issue here

### Issue Content

Tables are very used in educational and academic documents and is an essential feature for a text editor, here is the expected features from this Issue : 

- Ability to add a table 
- Should be easy to use, Notion and/or Google Docs is great inspiration
- Should use the Table extension from TipTap 

Documentation : 

https://tiptap.dev/docs/editor/api/nodes/table

**Comment by eduardconstantin** [comment]
could you assign this to me?
