### ISSUE TITLE
Optimize Editor's Collaboration features performance by debouncing websockets sends

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#200]
### Verified issue

- [X] Someone from the team allowed me to create an issue here

### Verified issue

- [X] Someone from the team allowed me to create an issue here

### Issue Content

Hi Everyone, 
Thanks for your interest in LearnHouse, this is a good first issue for anyone that want to contribute. 

### Issue Description:
Improve the collaborative experience in the Editor by improving its performance : 

- Debounce the number of requests that gets sent to the collab server 
  - Mouse Movements

### Difficulty Level: Easy/Intermediate/Advanced
Intermediate

### Expected Benefits:

- Better editor performance

### Code 

https://github.com/learnhouse/learnhouse/blob/28c7def56ad7e788cd742c411f114350e36f8ec8/apps/web/components/Objects/Editor/EditorWrapper.tsx#L56

**Comment by swve** [comment]
Hello @eduardconstantin , yes it is and if you need any help you're welcome in our Discord : https://discord.com/invite/CMyZjjYZ6x

**Comment by eduardconstantin** [comment]
Thank you! I will join but please assign me to this issue.

**Comment by swve** [comment]
Here you go @eduardconstantin !

**Comment by eduardconstantin** [comment]
@swve I created a PR for this issue

**Comment by swve** [comment]
Thanks @eduardconstantin i'll be looking into this soon

**Comment by AQIB-NAWAB** [comment]
@swve can i contribute to this issue ?

**Comment by eduardconstantin** [comment]
@AQIB-NAWAB of course not, I already made a PR for this issue

**Comment by swve** [comment]
fixed by #326
