### ISSUE TITLE
[Bug]: Organization not found

### ISSUE THREAD

**Issue by PVUL** [learnhouse/learnhouse#223]
### What happened?

First off, awesome project.

The issue I'm running into on the `dev` branch off a fresh clone:

```bash
⨯ services/utils/ts/requests.ts (80:23) @ errorHandling
 ⨯ Error: Not Found
    at errorHandling (./services/utils/ts/requests.ts:84:23)
    at getOrganizationContextInfo (./services/organizations/orgs.ts:31:97)
    at async Module.generateMetadata$1 (page.tsx:57:17)
  78 | export const errorHandling = (res: any) => {
  79 |   if (!res.ok) {
> 80 |     const error: any = new Error(`${res.statusText}`)
     |                       ^
  81 |     error.status = res.status
  82 |     throw error
  83 |   }
 ⨯ services/utils/ts/requests.ts (80:23) @ errorHandling
 ⨯ Error: Not Found
    at errorHandling (./services/utils/ts/requests.ts:84:23)
    at getOrganizationContextInfo (./services/organizations/orgs.ts:31:97)
    at async Module.generateMetadata$1 (page.tsx:57:17)
digest: "2148548821"
  78 | export const errorHandling = (res: any) => {
  79 |   if (!res.ok) {
> 80 |     const error: any = new Error(`${res.statusText}`)
     |                       ^
  81 |     error.status = res.status
  82 |     throw error
  83 |   }
  ...
  ```

Steps to reproduce:

1. Run `git clone git@github.com:learnhouse/learnhouse.git`  
2. Run `docker compose up -d`
3. Run `cd apps/web && pnpm i && pnpm run dev`
4. Visit `http://localhost:3000` and see the error in terminal logs.

Screenshot:
<img width="879" alt="Screenshot 2024-04-16 at 6 32 08 PM" src="https://github.com/learnhouse/learnhouse/assets/9632017/38f89ece-d060-4484-94bb-9b0a61691def">

---

Looks like it could be related to no `orgslug` being provided in the url params.

### Version

dev

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swve** [comment]
Hello @PVUL, Happy to know that you like the project 😄 

It seems like the organization you've specified in your env variable isn't found on the database, did you install learnhouse before running the app in the dev environment ? https://docs.learnhouse.app/setup-dev-environment

**Comment by swve** [comment]
@PVUL The documentation has been updated, you should not have any issues with the new Guide
