### ISSUE TITLE
Easy self hosting using a CLI 

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#225]
### Issue Content

- Install LearnHouse with predefined Creds, Organizations etc. 
- Make it easy to pop a self hosted instance of LearnHouse locally 
- Use Typer for the CLI with Python 

### Is this issue planned ?

- [X] Planned

**Comment by swve** [comment]
Hello @zahidhanif, thanks a lot for your kind words. 

Absolutely I've seen that a lot of people struggle with the installation process, and i'm looking to to make this a simple as possible with a step by step CLI to run the app using docker or on the system itself, however i'll be happy to help on [Discord](https://discord.com/invite/CMyZjjYZ6x) if you're still having the issue. 

I'd be also interested to know about your ideas and what the perfect LMs would look like! 
Thanks

**Comment by zahidhanif** [comment]
Thanks, I will join Discord and share my errors and my thoughts/needs for a LMS.
