### ISSUE TITLE
Mobile friendly website

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#319]
- Make the public side of the app mobile friendly (responsive)
- Make some parts of the dashboard responsive.

**Comment by sankettank66** [comment]
Hello @swve,

I would like to work on this issue. Could you please assign it to me?

**Comment by swve** [comment]
Hey @sankettank66, I appreciate the help but I will work personally work on this Issue.

**Comment by sankettank66** [comment]
> Hey @sankettank66, I appreciate the help but I will work personally work on this Issue.

No problem @swve 
Thank you for the reply.
