### ISSUE TITLE
[Bug]: bug when launching docker

### ISSUE THREAD

**Issue by rvmadeit** [learnhouse/learnhouse#329]
### What happened?

When i try to deploy via the command docker-compose up -d the docker have a proble when trying to create an optimized production build. I try with and without .env.

Heres my version:
docker version : 27.3.1
docker compose version: 2.29.7

 

### Version

dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dhanyamd** [comment]
same :(

**Comment by swve** [comment]
Hello, can you share some logs ?

**Comment by rvmadeit** [comment]
![image](https://github.com/user-attachments/assets/e0e48abb-7a7e-406a-8418-6373db9a1b87)

**Comment by swve** [comment]
@rvmadeit from your logs, it looks like the process has been killed, this may have been an issue with CPU or RAM allowance on your machine. 

- Try to increase your memory/cpu limit in Docker and try again 

The Kill may also mean that an error happened, but I don't think it's the case, as I built multiple times the project this week and some people from the community, and there is no known issues on the frontend side as for now.
