### ISSUE TITLE
[Bug]: Ui bleeding in multiple page  on medium screen

### ISSUE THREAD

**Issue by Abhii5496** [learnhouse/learnhouse#338]
### Contact Details

abhiiv5496@gmail.com

### What happened?

Ui is messed up on tablets
1. Landing Page
![image](https://github.com/user-attachments/assets/d5a9a8c6-3318-420b-b612-6ab78bbdf0a6)

2. Pricing Page
![image](https://github.com/user-attachments/assets/593ba735-3c91-495c-b8f5-e6f8a1317220)

3.Ai Page
![image](https://github.com/user-attachments/assets/ae4b3b83-1559-4354-980b-265d875abec7)

4. Changelog Page
![image](https://github.com/user-attachments/assets/66bd82ba-f120-4345-bf05-532fa8876207)
and more..

if its okay i can work on it .

### Version

1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swve** [comment]
Thanks for sharing @Abhii5496, this is part of the internal code base. I'll look into it soon but the mobile version is already working properly
