### ISSUE TITLE
[Bug Tracker]: Compilation of known bugs for the Alpha version

### ISSUE THREAD

**Issue by chrishollandaise** [learnhouse/learnhouse#341]
### What happened?

This issue serves as a compilation of bugs known to us so far. This serves as a nice way of tracking progress for stabilizing LearnHouse's beta release 

## Bugs

- [x] #351

- [x] #357 

- [x] #344 

- [x] #359 

- [x] #352

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/fc79786b-cd5d-4277-b038-737af51f4883

</details>

- [x] #366

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/b0c9bfd2-5476-48df-bcfa-45e33a99c12c

</details>

- [x] #343 

- [x] #342 

- [x] #350

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/92b34afd-1742-49c3-a6cf-641985519f1d

</details>

- [x] #360 

- [x] #349

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/432f721a-4b86-4507-86d5-59984859734a

</details>

- [x] #347

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/e56efd86-a2e8-4d00-8de3-716de3152155

</details>

- [x] #355

- [x] #346

<details>
<summary>Demos</summary>

https://github.com/user-attachments/assets/99fcddbe-c4fa-4e66-b146-648faaa055d7

https://github.com/user-attachments/assets/e584917d-1223-4ec8-a78e-adf96bb87396

</details>

- [x] #365

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/8802cc39-8a64-4f23-bb22-f112367170d4

</details>

- [x] #364

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/4bb5d62f-5937-4672-88b4-cdd46198c4ba

</details>

- [x] #363

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/5a536a1c-cd3c-4b65-9b1d-6f0fad6b4293

</details>

- [x] #362

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/c8425bdc-b79f-40bf-b839-531076b2ac1a

</details>

- [x] #375 

- [x] #396

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/38a815b2-0938-43b4-9e41-82cf965f6ee7

</details>

- [x] #394

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/38a815b2-0938-43b4-9e41-82cf965f6ee7

</details>

- [x] #393

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/febf3214-650d-40b4-961a-b6ad4ed799a8

</details>

- [x] #392

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/1083ae27-dc3d-4063-8d22-10a542b0b8ba

</details>

- [x] #395

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/64620361-d1c4-49e6-acfe-a891dd6b8267

</details>

- [x] #391

<details>
<summary>Demo</summary>

https://github.com/user-attachments/assets/66d7a657-d995-4e5b-b543-cbb1687b0f49

</details>

- [x] #356 

### Version

dev @ 0fe55b3

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swve** [comment]
Hey @chrishollandaise, thanks a bunch for this list!

I’m definitely pinning it—it’s a goldmine to have all these known bugs in one place. I knew about a few but never got around to fixing or logging them. This is super helpful, especially with the beta release of LearnHouse coming up (hopefully for end of the year)!

Tbh, we can turn all of these into issues so the community can jump in and help!

Really appreciate all the effort you put into this 🙌 Thanks again!

**Comment by chrishollandaise** [comment]
> Hey @chrishollandaise, thanks a bunch for this list!
> 
> I’m definitely pinning it—it’s a goldmine to have all these known bugs in one place. I knew about a few but never got around to fixing or logging them. This is super helpful, especially with the beta release of LearnHouse coming up (hopefully for end of the year)!
> 
> Tbh, we can turn all of these into issues so the community can jump in and help!
> 
> Really appreciate all the effort you put into this 🙌 Thanks again!

Absolutely @swve! I'll go ahead and convert them. I didn't want to bombard the issue tracker. I have even more bugs that I need to make issues for, so I'll continue to update this.

**Comment by chrishollandaise** [comment]
@swve Oh nevermind, I can't convert them into issues because I don't have the permissions

**Comment by swve** [comment]
@chrishollandaise No prob, I'll convert the most urgent ones for now :)

**Comment by swve** [comment]
That was one big of an Issue, I fixed the remaining issues/bugs that were still around and some new ones that I and other users reported. 

Again thanks a lot @chrishollandaise for the help with this really appreciate it!
