### ISSUE TITLE
[Bug]: Add correct accept attribute to file inputs across app to prevent odd behavior

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#346]
Found & recorded by @chrishollandaise 

https://github.com/user-attachments/assets/99fcddbe-c4fa-4e66-b146-648faaa055d7

**Comment by chrishollandaise** [comment]
There's also a discussion to be had about types of files we'd want to support especially for inputs that accept video. AFAIK, there only three main video formats that HTML supports playback for ([Ogg, MP4, and WebM)](https://en.wikipedia.org/wiki/HTML_video#Browser_support) with support for different codecs being more browser dependent.

This'll probably require a separate issue in itself. but @swve do we want LearnHouse to support only formats that can be played back within the browser? Or also allow other types of video formats that can be downloaded to a user's machine?

**Comment by swve** [comment]
@chrishollandaise I think we should stick with MP4 and WebM for now since they're compressed formats that will keep things simpler and lighter on the server. Later on, we could consider adding a conversion feature similar to YouTube, where users can upload any video format, and we handle converting it to H.264 on the server side but that would be for later versions. 

Some users have expressed concerns about easy video download and have asked to remove the download button from the native player that comes with most browsers when using `<video>`. I’m not sure if we can selectively disable specific elements of the native player, but I we’ll end up adding custom players like Video.js anyway, which should give us more control over the UI and allow us to hide features like the download button. 

Users will have the option to enable or disable video downloads, depending on their preference. What do you think?

**Comment by chrishollandaise** [comment]
Yeah, I agree with just supporting with MP4 and WebM. Nice to have, but not necessary for now.

AFAIK you can't really, there's some hacky solutions ([see StackOverflow post](https://stackoverflow.com/questions/9756837/prevent-html5-video-from-being-downloaded-right-click-saved#answer-9756909)). I agree that Video.js is better route.

I like that idea, user agency for these sorts of things is never bad.

**Comment by swve** [comment]
Yeah, we're on the same page. That StackOverflow post is interesting, and I think that streaming is the way to go. I originally wanted to implement it from the start but ended up going with something simpler. Some parts of the app are still from the MVP phase 😅

With streaming, even if users try to inspect requests in the devtools network tab, it would still be challenging for them to capture all the data chunks. I've noticed that many video-based streaming services, especially educational platforms, are using this approach.

**Comment by swve** [comment]
Fixed in https://github.com/learnhouse/learnhouse/pull/367
