### ISSUE TITLE
[Bug]: Inconsistent spacing for file acceptance disclaimer text for Logo Change component on Organization edit page

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#347]
Found & recorded by @chrishollandaise 

https://github.com/user-attachments/assets/e56efd86-a2e8-4d00-8de3-716de3152155

**Comment by DeviSriSaiCharan** [comment]
Hey, i would like to work on this, can you assign it to me?

**Comment by swve** [comment]
it is yours @DeviSriSaiCharan

**Comment by swve** [comment]
Fixed in #339. 
@DeviSriSaiCharan Wasn't much that challenging of an issue anyway, you can take other ones. 
Thanks
