### ISSUE TITLE
[Bug]: Inviting members with absurdly long email address extends the width of invited users element

### ISSUE THREAD

**Issue by swve** [learnhouse/learnhouse#350]
Found & recorded by @chrishollandaise 

https://github.com/user-attachments/assets/92b34afd-1742-49c3-a6cf-641985519f1d

**Comment by Benjamin-Frost** [comment]
Hi @swve, I'm interested in contributing to this project for Hacktoberfest and would love to work on this issue. Could I take a shot at it?

If so, which solution would you prefer? Some options that come to mind are:

- Extending the name to the next line
- Hiding the overflow
- Displaying an ellipsis at the end

**Comment by swve** [comment]
Hey @Benjamin-Frost, of course! 

I think the ellipsis at the end is the better option long term.

I've assigned the issue to you.

**Comment by chrishollandaise** [comment]
@Benjamin-Frost If you can, I'd test other inputs like this and provide the fixes to thoses as well. I know for a fact that UserGroups input is affected, there's probably. 

The hiding the overflow is not a bad idea, especially if you use the `overflow-x: scroll` style. That way the email is not truncated.
