### ISSUE TITLE
How to add migrations

### ISSUE THREAD

**Issue by MikMuellerDev** [learnhouse/learnhouse#386]
### Issue Content

Hello,
I am currently digging my way through this project as I'd like to contribute in the long term.
Therefore i am wondering how i would another database migration (i use Linux).

**Comment by swve** [comment]
Hello Mik, We use alembic for SQL Migrations, you can check docs about it but tldr here is how it works 

To generate a revision with the changes you did on your DB : `alembic revision --autogenerate -m "Payments" `
Check your migrations history : `alembic history`
Do all the migrations :`alembic upgrade head`
Downgrade migrations : `alembic downgrade -2`

Migrations folder is here and you can check the migrations that has been done on the database https://github.com/learnhouse/learnhouse/tree/dev/apps/api/migrations 

Don't hesitate if you have further questions
